### PR TITLE
Fixes #51

### LINKED ISSUE #51: React-DOM is no longer  "secretly" included in React > 15.4.0 (CSSProperty require from react = error)
Since [release 15.4.0](https://github.com/facebook/react/releases/tag/v15.4.0), React package and browser build no longer "secretly" includes React DOM.

Resulting in

```
Failed to compile.

Error in ./~/draft-js-export-html/lib/helpers/styleToCSS.js
Module not found: 'react/lib/CSSProperty' in /Users/orditeck/Sites/MyProject/frontend/node_modules/draft-js-export-html/lib/helpers

 @ ./~/draft-js-export-html/lib/helpers/styleToCSS.js 7:19-51
```

Coming [from this line](https://github.com/sstur/draft-js-export-html/blob/master/src/helpers/styleToCSS.js#L3), `var _CSSProperty = require('react/lib/CSSProperty');`

I'll open a pull request in a few minutes.

### PR DESCRIPTION
**Pull request by orditeck**

### CODE REVIEW

**Comment by meggantodd** [comment]
I need this fix too :)

**Comment by terencechow** [comment]
+1

**Comment by darcyadams** [comment]
FYI... Dan Abramov tweeted  [this](https://twitter.com/dan_abramov/status/798926305030877184) today.
I would vote for merging this fix as a stop gap, but finding an alternative approach ASAP.

**Comment by sstur** [comment]
Thanks for the fix! This has been published to npm.

**Pull request merged**
