### PR TITLE
Adding video and audio entity support

### PR DESCRIPTION
**Pull request by daumann**
This PR also requires a change in draft-js-utils (see my PR there) which ultimately means also an up-step of draft-js-utils in package.json.

Related PR: https://github.com/sstur/draft-js-utils/pull/1

### CODE REVIEW

**Comment by NamitYadav** [comment]
Hi, When will this be merged?

**Comment by daumann** [comment]
You have to ask @sstur

**Comment by sstur** [comment]
Hi @daumann. Thanks for your contribution to this project.

As of now, the supported way to add custom block element support is to use `blockRenderers` which is [documented in the README](https://github.com/sstur/draft-js-export-html#blockrenderers).

Let me know if this works for your use case. I'm closing this for now since I don't plan to support those elements in core.

**Comment by ericharding** [comment]
I hate to bump such an old thread.  I'm strugging to get a video element working using the blockRenderers method.  Do either of you know if there's a more complete example of a custom blockRender including how to insert the custom block from the toolbar?

**Comment by volkandkaya** [comment]
@ericharding did you get it working?

**Comment by ericharding** [comment]
I did get it working but not with a new blockRender. I ended up forking and modifying the ImageSpan to detect youtube video links so you can use the existing image button but paste a video link and it renders the thumbnail automatically.

https://github.com/clinwiki-org/react-rte/commit/e5781759bce89cdc7dc992d7be46196a9058d5f6

**Pull request closed without merging**
