### PR TITLE
Add failing test case for code blocks

### PR DESCRIPTION
**Pull request by mxstbr**
Ref #94

### CODE REVIEW

**Comment by mxstbr** [comment]
Hmm, the test receives a correct state so `draft-js-import-element` works fine with `<pre><code>` code blocks:

screen shot 2017-09-17 at 8 01 24 pm

I went ahead and manually tested the markdown parser from `draft-js-import-markdown`, that also returned the correct `pre/code` AST:

```JS
import MarkdownParser from 'draft-js-import-markdown/lib/MarkdownParser';

const markdown = '```\nconst a = \'b\';\n```'; // Code block in markdown

console.log(MarkdownParser.default.parse(markdown, { getAST: true }))

// Which logs

{
   "nodeType":1,
   "_name":"body",
   "attributes":[],
   "_attrMap":{},
   "nodeName":"BODY",
   "childNodes":[
      {
         "nodeType":1,
         "_name":"pre",
         "attributes":[

         ],
         "_attrMap":{

         },
         "nodeName":"PRE",
         "childNodes":[
            {
               "nodeType":1,
               "_name":"code",
               "attributes":[

               ],
               "_attrMap":{

               },
               "nodeName":"CODE",
               "childNodes":[
                  "const a = 'b';"
               ],
               "_isSelfClosing":false
            }
         ],
         "_isSelfClosing":false
      }
   ],
   "_isSelfClosing":false
}
```

But when I use `draft-js-import-markdown` directly it doesn't work:

```JS
import { convertToRaw } from 'draft-js';
import { stateFromMarkdown } from 'draft-js-import-markdown';

const markdown = '```\nconst a = \'b\';\n```'; // Code block in markdown

console.log(convertToRaw(stateFromMarkdown(markdown)))

// This logs

{
  "entityMap": {},
  "blocks": [
    {
      "key": "b0bcm",
      "text": "",
      "type": "unstyled",
      "depth": 0,
      "inlineStyleRanges": [],
      "entityRanges": [],
      "data": {}
    }
  ]
}
```

This thusly has got to have something to do with the interplay between the markdown parser and `draft-js-import-element`. @sstur any ideas what the issue could be?

**Comment by mxstbr** [comment]
Okay, I've fixed the `import-element` test since that works and added a failing test to `import-markdown` which clearly shows the issue.

I still have no idea how to add support for code blocks, so I'm hoping @sstur has an idea and can take this PR forward. 🙃

**Comment by mxstbr** [comment]
This is now failing as expected: 

screen shot 2017-09-17 at 8 22 00 pm

So code blocks are just deleted rather than moved over.

**Comment by mxstbr** [comment]
I've traced it down to these lines:

https://github.com/sstur/draft-js-utils/blob/850fe14287fdf248f9d7d7c1a55d40dd1cc5dbd0/packages/draft-js-import-element/src/stateFromElement.js#L224-L227

Above this line, `contentBlocks` looks right with the `CODE` blocks:

screen shot 2017-09-17 at 8 43 16 pm

But then obviously once this function runs the code blocks are deleted, which leads me to think that `this.contentStateForEntities.getEntityMap()` returns something incorrect maybe?

**Comment by sstur** [comment]
Thanks @mxstbr, you've done most of the hard part for me! I'll take a look now and see if I can figure out why `stateFromElement` is failing us.

EDIT: I think I almost have this figured out. I do not believe it is those lines 224-227 tho. It seems to be before that.

**Comment by sstur** [comment]
Take a quick peek at #98 and let me know if you have any feedback. Thanks!

**Comment by sstur** [comment]
Fixed in #98

**Pull request closed without merging**
