### PR TITLE
Fix markdown parsing for italic

### LINKED ISSUE #251: Markdown Italic does not work with word selected in middle
The markdown for italic does not work in the scenario:

aaaaa _bbbbb _ccccc"

After we save this änd try to read in the Rich Text editor the word "bbbbb" will not show in italic instead it will show "_bbbbb _".

Is there any support on this project... will a merge request be accepted if we provided a viable solution?

### PR DESCRIPTION
**Pull request by msglifeIberia**
Fixes #251:

1. Changed regex to support issue described in #251 
2. Add tests for italic and bold markdown characters

### CODE REVIEW

**Review by sstur — APPROVED** [review]
Looks good to me, thanks for adding such comprehensive tests!

**Comment by MSGInsurIt** [comment]
@sstur, Is a new release going to be created for this fix?

**Comment by sstur** [comment]
Yes, will do a release this week. Will post back here when done.

**Comment by sstur** [comment]
Done. draft-js-utils@1.4.1 is published.

**Comment by MSGInsurIt** [comment]
@sstur will you be merging this code again... The safari release has been created with the support for negative lookbehind expressions:

Negative lookbehind assertion It's working now in Release 161 of Safari Technology Preview, downloads are here: [https://developer.apple.com/safari/resources/]
[Safari Technology preview 161](https://webkit.org/blog/13686/release-notes-for-safari-technology-preview-161/)
Although it didn't make the cut for the release notes!

**Pull request merged**
